sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
  - 12
os:
  - linux
before_script:
  - npm i -g npm
  - npm install
  - npm i codecov
  - npm run test:ci
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
