meta:
  url: https://slide.hiroppy.me
  name: Fusuma
  author: hiroppy
  description: Introduce Fusuma
  thumbnail: url
  siteName: hiroppy.me
  repositoryUrl: https://github.com/hiroppy/fusuma
  sns: ['twitter']
slide:
  theme: nebula
extends:
  js: index.js
  css: style.css
